default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  url: <%= ENV['POSTGRESS_URL_DEVELOPMENT']%>
staging:
  <<: *default
  url: <%= ENV['POSTGRESS_URL_STAGING']%>
production:
  <<: *default
  url: <%= ENV['POSTGRESS_URL_PRODUCTION']%>

test:
  <<: *default
  database: test_dev
